name: pixiv_func_mobile
description: Pixiv 第三方客户端

publish_to: 'none'
version: 1.0.0-beta56+62

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.5.0
  get: ^4.6.5
  dio: ^5.2.1+1
  crypto: ^3.0.3
  intl: ^0.18.0
  mutex: ^3.0.1
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4
  extended_image: ^8.0.2
  extended_nested_scroll_view: ^6.1.0
  extended_sliver:
    git: https://github.com/git-xiaocao/extended_sliver.git
  waterfall_flow: ^3.0.2
  pull_to_refresh_notification: ^3.0.1
  loading_more_list: ^5.0.3
  html: ^0.15.3
  permission_handler: ^10.3.0
  image_picker: ^0.8.7+5
  file_picker: ^5.3.2
  encrypt: ^5.0.1
  device_info_plus: ^9.0.2
  connectivity_plus: ^4.0.1
  expandable: ^5.0.1
  visibility_detector: ^0.3.3
  path: ^1.8.3
  uni_links2: ^0.6.0+2
  share_plus: ^7.0.2
  path_provider: ^2.0.15
  app_installer: ^1.1.0
  flutter_local_notifications: ^14.1.1
  pixiv_live_proxy_server:
    path: ../pixiv_live_proxy_server
  extended_text: ^11.0.1
  extended_text_field: ^12.0.0
  video_player: ^2.6.1
  #  唤醒锁
  wakelock: ^0.6.2
  #  设备方向 dart3不兼容
#  orientation: ^1.3.0
  auto_orientation: ^2.3.1
  image_editor: ^1.3.0
  pixiv_dart_api:
#    git: https://github.com/git-xiaocao/pixiv_dart_api.git
    path: ../pixiv_dart_api
  quick_actions: ^1.0.5
  share_handler: ^0.0.16
  synchronized: ^3.1.0
  # 增大点击范围
  extra_hittest_area: ^0.1.0
dependency_overrides:
  win32: ^5.0.0
dev_dependencies:
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/stamps/
    - assets/emojis/
  fonts:
    - family: iconFont
      fonts:
        - asset: assets/icon.ttf
